name: Deploy to Firebase Hosting on PR
on:
  push:
    branches:
      - main
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_deploy:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Inspect Service Account Email
        run: |
          echo "The service account email is:"
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PTPROJECTSWEB }}' | jq -r '.client_email' | sed 's/./& /g'
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      
      # 1. Authenticate using the official Google Auth step
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PTPROJECTSWEB }}
          
      # 2. Deploy to Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          projectId: ptprojectsweb